# Generated by Django 4.1.1 on 2022-11-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
