# Generated by Django 4.1.1 on 2022-11-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_category', '0001_initial'),
        ('bookstore_products', '0004_book_author_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, to='bookstore_category.bookcategory'),
        ),
    ]
