# Generated by Django 3.2.15 on 2022-12-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_products', '0005_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
