# Generated by Django 3.2.15 on 2022-12-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_products', '0006_book_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
