# Generated by Django 3.2.15 on 2022-12-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_products', '0008_book_edition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='book_pic',
        ),
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
