# Generated by Django 3.2.15 on 2022-12-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_products', '0009_auto_20221227_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_pic',
            new_name='image',
        ),
    ]
