# Generated by Django 3.2.15 on 2022-12-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_products', '0011_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
