# Generated by Django 3.2.15 on 2022-12-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_products', '0012_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Date',
            field=models.DateTimeField(null=True),
        ),
    ]
