# Generated by Django 3.2.15 on 2022-12-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_comments', '0003_alter_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
