# Generated by Django 3.2.15 on 2022-12-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishdetail',
            old_name='wish_book',
            new_name='wishBook',
        ),
    ]
