# Generated by Django 3.2.15 on 2022-12-26 20:43

import bookstore_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Lateri109_EpgjFtz.jpg', null=True, upload_to=bookstore_account.models.upload_image_path),
        ),
    ]
