# Generated by Django 4.1.5 on 2023-01-31 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_account', '0004_alter_user_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='date_of_birth',
        ),
    ]
